2020-07-24 17:31:50,028 | ERROR | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014CB139B280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    239
2020-07-24 17:31:50,998 | ERROR | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014CB139B340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    239
